# -*- coding: utf-8 -*-
#
# visp_tk_tutorials documentation build configuration file, created by
# sphinx-quickstart on Mon Jun  1 14:21:53 2009.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
import shutil, os
import xml.etree.ElementTree as ET
from pathlib import Path

def find_package_root() -> Path:
    """
    Derive package root from rosdoc2's predictable temp path structure:
    <output>/<pkg>/<pkg>/wrapped_sphinx_directory/conf.py
    """
    here = Path(__file__).resolve()

    # Extract package name from the temp path structure
    # path: .../wrapped_sphinx_directory/conf.py
    # go up: wrapped_sphinx_directory -> <pkg> -> <pkg> -> output_dir -> workspace
    parts = here.parts
    try:
        idx = parts.index("wrapped_sphinx_directory")
        # The package name is the directory just before wrapped_sphinx_directory
        pkg_name = parts[idx - 1]
        # The workspace root is 3 levels above wrapped_sphinx_directory
        # (wrapped_sphinx_directory -> <pkg> -> <pkg> -> output_dir -> workspace)
        output_dir = Path(*parts[: idx - 2])
        workspace = output_dir.parent
    except (ValueError, IndexError):
        raise RuntimeError(f"Unexpected rosdoc2 path structure: {here}")

    # os.walk with followlinks=True handles symlinked package directories
    for dirpath, dirnames, filenames in os.walk(workspace, followlinks=True):
        # Don't descend into the rosdoc2 output directory
        dirnames[:] = [d for d in dirnames if d != output_dir.name]
        if ("doc" in dirnames) and ("package.xml" in filenames):
            candidate = Path(dirpath) / "package.xml"
            if ET.parse(candidate).getroot().findtext("name") == pkg_name:
                return Path(dirpath)

    raise RuntimeError(
        f"Could not find package '{pkg_name}' under workspace '{workspace}'"
    )

def find_desired_package_root(pkg_name: str) -> Path:
    """
    Derive package root from rosdoc2's predictable temp path structure:
    <output>/<pkg>/<pkg>/wrapped_sphinx_directory/conf.py
    """
    here = Path(__file__).resolve()

    # Extract package name from the temp path structure
    # path: .../wrapped_sphinx_directory/conf.py
    # go up: wrapped_sphinx_directory -> <pkg> -> <pkg> -> output_dir -> workspace
    parts = here.parts
    try:
        idx = parts.index("wrapped_sphinx_directory")
        # The workspace root is 3 levels above wrapped_sphinx_directory
        # (wrapped_sphinx_directory -> <pkg> -> <pkg> -> output_dir -> workspace)
        output_dir = Path(*parts[: idx - 2])
        workspace = output_dir.parent
    except (ValueError, IndexError):
        raise RuntimeError(f"Unexpected rosdoc2 path structure: {here}")

    # os.walk with followlinks=True handles symlinked package directories
    for dirpath, dirnames, filenames in os.walk(workspace, followlinks=True):
        # Don't descend into the rosdoc2 output directory
        dirnames[:] = [d for d in dirnames if d != output_dir.name]
        if ("msg" in dirnames) and ("package.xml" in filenames):
            candidate = Path(dirpath) / "package.xml"
            if ET.parse(candidate).getroot().findtext("name") == pkg_name:
                return Path(dirpath)
    return None

PACKAGE_ROOT = find_package_root()
MSG_PACKAGE_ROOT = find_desired_package_root("visp_tracker_common")
PACKAGE_NAME = ET.parse(PACKAGE_ROOT / "package.xml").getroot().findtext("name")
DOC_ROOT = PACKAGE_ROOT / "doc"
SNIPPET_ROOT = DOC_ROOT / "_code"
SOURCE_DIRS = ["config", "launch"]

def setup(app):
    SNIPPET_ROOT.mkdir(exist_ok=True)

    for d in SOURCE_DIRS:
      src = PACKAGE_ROOT / d
      dst = SNIPPET_ROOT / d

      if src.exists():
          if dst.exists():
              shutil.rmtree(dst)
          shutil.copytree(src, dst)

    if MSG_PACKAGE_ROOT is not None:
      d = "msg"
      src = MSG_PACKAGE_ROOT / d
      dst = SNIPPET_ROOT / d
      if src.exists():
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.coverage',
    'sphinx_rtd_theme',
    'myst_parser'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = ['.rst', '.md', '.py']

# The encoding of source files.
#source_encoding = 'utf-8'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'visp_tk_tutorials'
copyright = '2004-2026, ViSP'

# The full version, including alpha/beta/rc tags.
release = '0.1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of documents that shouldn't be included in the build.
#unused_docs = []

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  Major themes that come with
# Sphinx are currently 'default' and 'sphinxdoc'.
html_theme = 'default'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_use_modindex = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# If nonempty, this is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = ''

# Output file base name for HTML help builder.
htmlhelp_basename = 'visp_tk_tutorials_doc'


# -- Options for LaTeX output --------------------------------------------------

# The paper size ('letter' or 'a4').
#latex_paper_size = 'letter'

# The font size ('10pt', '11pt' or '12pt').
#latex_font_size = '10pt'


# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# Additional stuff for the LaTeX preamble.
#latex_preamble = ''

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_use_modindex = True

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('http://docs.python.org/', None),
    'numpy': ('http://docs.scipy.org/doc/numpy', None)
}
