<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>visp_apriltag</name>
  <version>0.1.0</version>
  <description>Package that allows to use an AprilTag / Aruco tag tracker using ViSP library.</description>
  <maintainer email="fabien.spindler@inria.fr">Fabien Spindler</maintainer>
  <author email="romain.lagneau@inria.fr">Romain Lagneau</author>
  <license>GPL-2.0-or-later</license>
  <url type="website">https://docs.ros.org/en/humble/p/visp_apriltag</url>
  <url type="repository">https://github.com/lagadic/visp_tk</url>
  <url type="bugtracker">https://github.com/lagadic/visp_tk/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>visp_common</depend>
  <depend>visp_tracker_common</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
