<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>visp_tracker_common</name>
  <version>0.1.0</version>
  <description>Package that contains the base classes and interfaces for the ViSP trackers packages + a GUI to display tracking results. </description>
  <maintainer email="Fabien.Spindler@inria.fr">Fabien Spindler</maintainer>
  <author email="romain.lagneau@inria.fr">Romain Lagneau</author>
  <license>GPL-2.0-or-later</license>
  <url type="website">https://docs.ros.org/en/humble/p/visp_tracker_common</url>
  <url type="repository">https://github.com/lagadic/visp_tk</url>
  <url type="bugtracker">https://github.com/lagadic/visp_tk/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>image_transport_plugins</depend>
  <depend>message_filters</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>vision_msgs</depend>
  <depend>visp_common</depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
