<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>visp_common</name>
  <version>0.1.0</version>
  <description>
    Converts between ROS structures and ViSP structures.
  </description>

  <maintainer email="Fabien.Spindler@inria.fr">Fabien Spindler</maintainer>
  <author>Fabien Spindler</author>
  <author email="romain.lagneau@inria.fr">Romain Lagneau</author>

  <license>GPL-2.0-or-later</license>

  <url type="website">https://docs.ros.org/en/humble/p/visp_common</url>
  <url type="repository">https://github.com/lagadic/visp_tk</url>
  <url type="bugtracker">https://github.com/lagadic/visp_tk/issues</url>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>camera_calibration_parsers</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>vision_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
