<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>visp_tk_tutorials</name>
  <version>0.1.0</version>
  <description>
    Package containing tutorials to learn how to use visp_tk packages.
  </description>
  <maintainer email="fabien.spindler@inria.fr">Fabien Spindler</maintainer>
  <author email="romain.lagneau@inria.fr">Romain Lagneau</author>
  <license>GPL-2.0-or-later</license>
  <url type="website">https://docs.ros.org/en/humble/p/visp_tk_tutorials</url>
  <url type="repository">https://github.com/lagadic/visp_tk</url>
  <url type="bugtracker">https://github.com/lagadic/visp_tk/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>rosbag2</exec_depend>
  <exec_depend>visp_tk</exec_depend>
  <exec_depend>v4l2_camera</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <!-- <rosdoc2>rosdoc2.yaml</rosdoc2> -->
  </export>
</package>
